sudo: required
dist: trusty
language: node_js
node_js:
    - node
addons:
apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
        - google-chrome-beta
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm i -g angular-cli-ghpages
script:
    - npm run lint
    - npm run sass-lint
    - npm run spell
    - npm run style
    - npm run test -- --watch=false
    #- npm run ng build -- --prod
    - npm run build -- --prod --base-href "/Angular-App/"
after_success:
    #- echo "musketeer.com" > dist/CNAME
    - ngh --repo=https://GH_TOKEN@github.com/tube-map-live/Angular-App.git --name="Travis CI" --email=dolan_miu@hotmail.com --no-silent --dir=dist/angular-app
